# Generated by Django 5.2 on 2025-05-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_joinrequst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoinRequst',
            new_name='JoinRequest',
        ),
    ]
